### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ryanpeach**
This contains the merge of my other two pull requests along with the bug fix for the issue I recently submitted.

### CODE REVIEW

**Comment by Zsailer** [comment]
For reference... This combines PR's #7 and #8.

**Comment by Zsailer** [comment]
This looks good. Thank you for making the changes to the argument names. 

As an aside, the newest release of networkx uses actual *arrows* for directed graphs (no longer using the rectangles). I don't think Vega has arrows just yet--so we may add that in the future. 

That said, I think this PR looks good. I'm going to merge it and release a new version of nx_altair in the next few days. 

Thanks @ryanpeach!

**Comment by ryanpeach** [comment]
Arrows would be possible with decent ease if you wanted them, as they are just lines with fixed length offset by an angle and mirrored along the edge. But it would double the number of graphical elements which I don't think is wise.

**Comment by ryanpeach** [comment]
Glad you liked it!

**Pull request merged**
